# Generated by Django 6.0.6 on 2026-06-04 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_type', models.CharField(choices=[('frontend', 'دستیار فرانت\u200cاند (Frontend Expert)'), ('backend', 'دستیار بک\u200cاند (Backend Expert)'), ('general', 'دستیار عمومی (General Assistant)')], max_length=20, verbose_name='نوع ایجنت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان شروع گفتگو')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'کاربر'), ('ai', 'هوش مصنوعی')], max_length=10, verbose_name='فرستنده')),
                ('content', models.TextField(verbose_name='متن پیام')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatsession', verbose_name='جلسه چت')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
